name: Sonarqube
run-name: ${{ github.actor }}

on:
  workflow_dispatch:  # Déclenchement manuel via GitHub avec des inputs
    inputs:
      version:
        description: 'Sonarqube'  # Description de l'input
        required: true  # Cet input est obligatoire
        default: 'latest'  # Valeur par défaut si l'utilisateur ne fournit rien
  push:
    branches:
      - sonarqube

jobs:


  start_Sonarqube_server:
    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ./.github/workflows
    
    outputs:    
      output1: ${{ steps.step1.outputs.test }}

    
    steps:
      

      # - name: get_ip
      #   id: ip-server
      #   run: |
      #     echo "IP_HOST_SERVER=ip -4 addr show | awk '/inet / && !/127.0.0.1/ && !/docker/ {print $2}'" >> "$GITHUB_OUTPUT"
      #     echo $GITHUB_OUTPUT
      
      # - name: shape address
      #   env:
      #       IP_HOST_SERVER: ${{steps.ip-server.outputs.IP_HOST_SERVER}}
      #   run: echo "IP=http://$IP_HOST_SERVER/" >> "$GITHUB_ENV"
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: step1
        run: ./script_ip >> "$GITHUB_OUPUT"

      - name: Démarrer le container SonarQube server
        run: docker run --name sonarqube-custom -p 9000:9000 sonarqube:10.6-community

  start_Sonar-scan:
    runs-on: ubuntu-latest
    needs: start_Sonarqube_server
    steps:
      - name: Wait for SonarQube server is ready 
        run : sleep 90

      - name: Official SonarQube Scan

        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarqube-scan-action@v1.1.0
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_USER }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on SonarQube, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
          SONAR_HOST_URL: ${{needs.start_Sonarqube_server.outputs.output1}} # add the URL of your instance to the secrets of this repo with the name SONAR_HOST_URL (Settings > Secrets > Actions > add new repository secret)
        with:
          # Additional arguments for the sonarcloud scanner
          args:
            # Unique key of your project. You can find it in SonarQube > [my project] > Project Information (top-right menu)
            # mandatory
            -Dsonar.projectKey=${{ vars.PROJECT_KEY }}
            # Comma-separated paths to directories containing main source files.
            #-Dsonar.sources= # optional, default is project base directory
            # When you need the analysis to take place in a directory other than the one from which it was launched
            #-Dsonar.projectBaseDir= # optional, default is .
            # Comma-separated paths to directories containing test source files.
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
            # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
            #-Dsonar.verbose= # optional, default is false
